spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: wangchao
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#logging:
#    level:
#        com.nowcoder.community: debug

